/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sunrisechina_SSJar */

#ifndef _Included_com_sunrisechina_SSJar
#define _Included_com_sunrisechina_SSJar
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sunrisechina_SSJar
 * Method:    encrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sunrisechina_SSJar_encrypt
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_sunrisechina_SSJar
 * Method:    decrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sunrisechina_SSJar_decrypt
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
